import { Athlete, AthleteCompetition, Competition } from "@/types";
import { BaseRecord } from "@refinedev/core";

export const mockAthletes: Athlete[] = [
    {
        id: 1,
        name: "Shounit Kamboj",
        gender: "male",
        dateOfBirth: "2003-04-15",
        email: "shounit@email.com",
        phone: "604-000-0000",
        weightClass: "93",
        equipment: "Classic",
        PRSquat: 220,
        PRBench: 140,
        PRDeadlift: 260,
        PRTotal: 620,
        coachId: 1,
        coach: { id: 1, name: "Coach Mike" },
        joinedAt: "2024-01-10",
        isActive: true,

        trainingBlock: {
            id: 1,
            coachId: 1,
            athleteId: 1,
            startDate: "2026-06-01",
            endDate: "2026-08-01",
            nextUpdateDate: "2026-07-14",
            daysTillUpdate: 7,
        },

        payment: {
            id: 1,
            coachId: 1,
            athleteId: 1,
            amount: 150,
            overdue: true,
            dueDate: "2026-06-10",
            paymentStatus: "overdue",
        },

        nextCompetitionDetails: {
            id: 1,
            athlete: {} as Athlete,
            athleteId: 1,
            competitionId: 1,
            competition: {
                id: 1,
                name: "CPU Nationals 2026",
                startDate: "2026-08-02",
                endDate: "2026-08-04",
                location: "Toronto, ON",
                url: "https://www.cpu.ca",
            },
            date: "2026-08-02",
            weighInTime: "07:00",
            startTime: "09:00",
            createdAt: "2026-06-01",
            updatedAt: "2026-06-01",
        },

        createdAt: "2024-01-10",
        updatedAt: "2026-07-01",
        notes: "",
        deleted: false,
    },

    {
        id: 2,
        name: "Alex Chen",
        gender: "male",
        dateOfBirth: "2002-09-22",
        email: "alex@email.com",
        weightClass: "74",
        equipment: "Classic",
        PRSquat: 180,
        PRBench: 120,
        PRDeadlift: 220,
        PRTotal: 520,
        coachId: 1,
        coach: { id: 1, name: "Coach Mike" },
        joinedAt: "2024-03-01",
        isActive: true,

        trainingBlock: {
            id: 2,
            coachId: 1,
            athleteId: 2,
            startDate: "2026-06-01",
            endDate: "2026-08-01",
            nextUpdateDate: "2026-07-21",
            daysTillUpdate: 14,
        },

        payment: {
            id: 2,
            coachId: 1,
            athleteId: 2,
            amount: 150,
            overdue: false,
            dueDate: "2026-07-30",
            paymentStatus: "paid",
        },

        createdAt: "2024-03-01",
        updatedAt: "2026-07-01",
        notes: "",
        deleted: false,
    },

    {
        id: 3,
        name: "Jordan Park",
        gender: "female",
        dateOfBirth: "2009-12-05",
        email: "jordan@email.com",
        weightClass: "59",
        equipment: "Equipped",
        PRSquat: 140,
        PRBench: 80,
        PRDeadlift: 160,
        PRTotal: 380,
        coachId: 1,
        coach: { id: 1, name: "Coach Mike" },
        joinedAt: "2025-01-15",
        isActive: true,

        trainingBlock: {
            id: 3,
            coachId: 1,
            athleteId: 3,
            startDate: "2026-06-15",
            endDate: "2026-09-01",
            nextUpdateDate: "2026-07-28",
            daysTillUpdate: 21,
        },

        payment: {
            id: 3,
            coachId: 1,
            athleteId: 3,
            amount: 150,
            overdue: false,
            dueDate: "2026-08-01",
            paymentStatus: "unpaid",
        },

        nextCompetitionDetails: {
            id: 2,
            athlete: {} as Athlete,
            athleteId: 3,
            competitionId: 2,
            competition: {
                id: 2,
                name: "BC Provincials 2026",
                startDate: "2026-09-05",
                endDate: "2026-09-06",
                location: "Vancouver, BC",
                url: "https://www.bcpowerlifting.ca",
            },
            date: "2026-09-05",
            weighInTime: "08:00",
            startTime: "10:00",
            createdAt: "2026-06-15",
            updatedAt: "2026-06-15",
        },

        createdAt: "2025-01-15",
        updatedAt: "2026-07-01",
        notes: "",
        deleted: false,
    },
];

export const mockCompetitions: Competition[] = [
    {
        id: 1,
        name: "CPU Nationals 2026",
        startDate: "2026-08-02",
        endDate: "2026-08-04",
        location: "Toronto, ON",
        url: "https://www.cpu.ca",
    },
    {
        id: 2,
        name: "BC Provincials 2026",
        startDate: "2026-09-05",
        endDate: "2026-09-06",
        location: "Vancouver, BC",
        url: "https://www.bcpowerlifting.ca",
    },
    {
        id: 3,
        name: "USAPL Raw Nationals 2026",
        startDate: "2026-11-10",
        endDate: "2026-11-14",
        location: "Spokane, WA",
        url: "https://www.usapowerlifting.com",
    },
];

export const mockAthleteCompetitions: AthleteCompetition[] = [
    {
        id: 1,
        athlete: mockAthletes[0],
        athleteId: 1,
        competitionId: 1,
        competition: mockCompetitions[0],
        date: "2026-08-02",
        weighInTime: "07:00",
        startTime: "09:00",
        createdAt: "2026-06-01",
        updatedAt: "2026-06-01",
    },
    {
        id: 2,
        athlete: mockAthletes[2],
        athleteId: 3,
        competitionId: 2,
        competition: mockCompetitions[1],
        date: "2026-09-05",
        weighInTime: "08:00",
        startTime: "10:00",
        createdAt: "2026-06-15",
        updatedAt: "2026-06-15",
    },
];

export const mockData: Record<string, BaseRecord[]> = {
    athletes: mockAthletes,
    competitions: mockCompetitions,
    "athlete-competitions": mockAthleteCompetitions,
};